<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>SoulHand</title>
    <link rel="stylesheet" href="<?php echo $_BASE; ?>css/app.css">
    <link rel="stylesheet" href="<?php echo $_BASE; ?>css/default.css">
    <link rel="stylesheet" href="<?php echo $_BASE; ?>css/controls.css">
    <link rel="stylesheet" href="<?php echo $_BASE; ?>css/emoticons.css">
    <link rel="stylesheet" href="<?php echo $_BASE; ?>css/main.css">
</head>
<body>
    <div id="app">
    <div class="content">
        <div class="body middle" id="home">
            <div class="container">
                <div class="souldhand"></div> 
                <h2 class="center">SoulHand</h2>         
                <div class="loadding"></div>
            </div>      
        </div>        
    </div>
</div>
<script src="<?php echo $_BASE; ?>VisionConfig.js" type="text/javascript"></script>
<script src="<?php echo $_BASE; ?>components/ciweb/min/JVision.js" type="text/javascript"></script>
<script src="<?php echo $_BASE; ?>components/aes/aes.js" type="text/javascript"></script>
<script src="<?php echo $_BASE; ?>components/highcharts/highcharts.js" type="text/javascript"></script>
<script src="<?php echo $_BASE; ?>components/jszip/dist/jszip.min.js" type="text/javascript"></script>
<script src="<?php echo $_BASE; ?>components/recordrtc/RecordRTC.min.js" type="text/javascript"></script>
<script src="<?php echo $_BASE; ?>js/build.js" type="text/javascript"></script>
</body>
</html>